[metadata]
name = nectar-health-probe
author = ARDC Nectar Cloud Services
author_email = coreservices@ardc.edu.au
license = Apache-2.0
summary = Container exec health probe for OpenStack worker processes
description_file =
    README.md
description_content_type = text/markdown
keywords = openstack, kubernetes, probe, oslo.messaging
home_page = https://github.com/NeCTAR-RC/nectar-health-probe
classifier =
    Environment :: OpenStack
    Intended Audience :: Information Technology
    Intended Audience :: System Administrators
    License :: OSI Approved :: Apache Software License
    Operating System :: POSIX :: Linux
    Programming Language :: Python
    Programming Language :: Python :: 3 :: Only
    Programming Language :: Python :: 3
    Programming Language :: Python :: 3.12
    Programming Language :: Python :: 3.14

[files]
packages = nectar_health_probe
include_package_data = True

[entry_points]
console_scripts =
    nectar-health-probe = nectar_health_probe.probe:main

[pbr]
skip_changelog=true
skip_authors=true
